version: "3.7"
services:
  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "LTg8B7BAxIemx7l2LNm1"
      MYSQL_DATABASE: "evergreen-db"
      MARIADB_RANDOM_ROOT_PASSWORD: "True"
    volumes:
      - "mariadb_data:/var/lib/mysql"
    ports:
      - "127.0.0.1:3306:3306"
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
   
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
    ports:
      - "81:80"
  
  api:
    depends_on: 
      - db
    build: .
    image: sgilz/evergreen-api:latest
    restart: always
    environment:
      DB_USER: "admin"
      DB_PASS: "LTg8B7BAxIemx7l2LNm1"
      DB_URI: db
      DB_PORT: '3306' 
      DB_NAME: 'evergreen-db'
    ports:
      - "5000:5000"

volumes:
  mariadb_data: